# Generated by Django 5.1.7 on 2025-12-13 15:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('symptoms', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='symptomentry',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.device'),
        ),
        migrations.AddField(
            model_name='symptomentry',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='riskscore',
            name='entry',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='risk_score', to='symptoms.symptomentry'),
        ),
        migrations.AddIndex(
            model_name='symptomentry',
            index=models.Index(fields=['device', 'entry_time'], name='symptoms_sy_device__de568d_idx'),
        ),
        migrations.AddIndex(
            model_name='symptomentry',
            index=models.Index(fields=['user', 'entry_time'], name='symptoms_sy_user_id_0f4806_idx'),
        ),
    ]
