# Generated by Django 5.1.7 on 2025-12-28 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symptoms', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='symptomentry',
            name='mood',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='symptomentry',
            name='pain_intensity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
