# Generated by Django 5.1.7 on 2025-12-13 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('reminder', 'Reminder'), ('campaign', 'Campaign'), ('system', 'System')], default='reminder', max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('cron_spec', models.CharField(blank=True, help_text='Cron format for recurring reminders', max_length=50, null=True)),
                ('next_send', models.DateTimeField(blank=True, null=True)),
                ('is_sent', models.BooleanField(default=False)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
